name: "Build and Deploy Server"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - 'prod'
          - 'dev'
        default: 'dev'

jobs:
  build_and_deploy_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create and populate .env file
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN_DEV: ${{ secrets.DISCORD_BOT_TOKEN_DEV }}
          DISCORD_BOT_TOKEN_PROD: ${{ secrets.DISCORD_BOT_TOKEN_PROD }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          # get connection details for postgres db
          DB_ID=$(doctl databases list | grep langbud-db-cluster-$ENVIRONMENT | awk '{print $1}')
          DB_DATA_JSON=$(doctl databases get $DB_ID --output json)
          PG_URI=$(echo $DB_DATA_JSON | jq -r .[].connection.uri)

          # get discord bot token
          if [ "$ENVIRONMENT" = "prod" ]; then
            DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN_PROD
          else
            DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN_DEV
          fi

          # create .env file with secrets
          cat <<EOF > .env
          OPENAI_API_KEY="$OPENAI_API_KEY"
          DISCORD_BOT_TOKEN="$DISCORD_BOT_TOKEN"
          PG_URI="$PG_URI"
          EOF

      - name: Build image 
        run: docker build -t ai-stuff-registry/langbud-server .

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Tag and push image to DO Container Registry
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          docker tag ai-stuff-registry/langbud-server registry.digitalocean.com/ai-stuff-registry/langbud-server:$ENVIRONMENT
          docker push registry.digitalocean.com/ai-stuff-registry/langbud-server:$ENVIRONMENT

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CI_CD_SSH_PRIVATE_KEY }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_langbud-server.key
          chmod 600 ~/.ssh/id_langbud-server.key

          export SSH_USER="langbud-server"
          export SSH_HOST="$(doctl compute droplet get langbud-server-$ENVIRONMENT --template {{.PublicIPv4}})"

          cat <<EOF > ~/.ssh/config
          Host langbud-server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_langbud-server.key
            StrictHostKeyChecking no
          EOF

      - name: Stop langbud-server service
        run: ssh langbud-server 'sudo systemctl stop langbud-server'

      - name: Start langbud-server service
        run: ssh langbud-server 'sudo systemctl start langbud-server'

      - name: Clean up DO Container Registry
        run: doctl registry garbage-collection start --include-untagged-manifests --force