name: Run DB Migrations Upgrade

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run db migrations against'
        required: true
        type: choice
        options:
          - 'prod'
          - 'dev'
        default: 'dev'

jobs:
  run_db_migrations_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install dbmt
        run: pip install git+https://github.com/trizko/dbmt

      - name: Run DB Migrations
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          # get connection details for postgres db
          DB_ID=$(doctl databases list | grep langbud-db-cluster-$ENVIRONMENT | awk '{print $1}')
          DB_DATA_JSON=$(doctl databases get $DB_ID --output json)
          PG_URI=$(echo $DB_DATA_JSON | jq -r .[].connection.uri)

          # run db migrations
          dbmt up --db-url $PG_URI --migrations-dir ./migrations